ALTER TABLE `account_avatar`
    CHANGE COLUMN `head` `head` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `id`,
    CHANGE COLUMN `body` `body` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `head`,
    CHANGE COLUMN `leg` `leg` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `body`,
    CHANGE COLUMN `armBack` `armBack` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `leg`,
    CHANGE COLUMN `armFront` `armFront` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `armBack`;
