CREATE TABLE `scroll_instance` (
    `id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
    `accountId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `scrollEntry` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
    `damage` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `destroyed` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `heal` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `idolKills` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `played` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `sacrificed` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `totalGames` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `unitKills` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `wins` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `tradable` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`)
);
